<template>
  <article class="condition-card summary-card">
    <div class="document-heading"><div class="doc-badge">Σ</div><div><p>历次检查结果汇总</p><h1>桥梁检查趋势与对比</h1><span>INSPECTION HISTORY SUMMARY</span></div><div class="doc-code"><small>初始检查</small><b>{{ summary.initialCount||0 }} 次</b><small>定期检查 {{ summary.periodicCount||0 }} 次</small></div></div>
    <div class="summary-chart-grid"><section><div class="summary-title"><b>定期检查等级趋势</b><span>数字越小，技术状况越好</span></div><div class="trend-bars"><article v-for="row in trendRows" :key="`rating-${row.code}`"><div class="bar rating" :style="{height:`${Math.max(12,row.rating*34)}px`}"><b>{{ row.rating||'—' }}</b></div><small>{{ row.date }}</small></article></div></section><section><div class="summary-title"><b>病害数量趋势</b><span>按检查期统计</span></div><div class="trend-bars"><article v-for="row in trendRows" :key="`defect-${row.code}`"><div class="bar defect" :style="{height:`${Math.max(12,Math.min(150,row.defects*7))}px`}"><b>{{ row.defects }}</b></div><small>{{ row.date }}</small></article></div></section></div>
    <section class="history-section"><div class="summary-title"><b>历次初始检查</b><span>{{ summary.initialCount||0 }} 个版本</span></div><el-table :data="summary.initialHistory||[]" border><el-table-column prop="date" label="检查日期"/><el-table-column prop="code" label="初始检查编号"/><el-table-column prop="version" label="版本" width="90"/><el-table-column prop="effective" label="有效状态" width="110"><template #default="{row}"><el-tag :type="Number(row.effective)===1?'success':'info'">{{ Number(row.effective)===1?'当前有效':'历史版本' }}</el-tag></template></el-table-column></el-table></section>
    <section class="history-section"><div class="summary-title"><b>历次定期检查</b><span>{{ summary.periodicCount||0 }} 个检查期</span></div><el-table :data="summary.periodicHistory||[]" border><el-table-column prop="date" label="检查日期"/><el-table-column prop="code" label="定期检查编号"/><el-table-column prop="rating" label="技术状况等级"/><el-table-column prop="defectCount" label="病害数量"/></el-table></section>
  </article>
</template>
<script setup>
import { computed } from 'vue'
const props=defineProps({summary:{type:Object,default:()=>({})}})
const trendRows=computed(()=> (props.summary.periodicHistory||[]).map(row=>({date:row.date,code:row.code,rating:Number(String(row.rating||'').match(/\d+/)?.[0]||0),defects:Number(row.defectCount||0)})))
</script>
<style scoped>
.condition-card{background:#fff;border:1px solid #cbd5e1;border-top:5px solid #334155;border-radius:8px;padding:26px 30px}.document-heading{display:grid;grid-template-columns:64px 1fr 210px;align-items:center;padding-bottom:22px;border-bottom:2px solid #0f172a}.doc-badge{width:52px;height:52px;display:grid;place-items:center;background:#334155;color:#fff;font:700 24px Georgia}.document-heading p,.document-heading span{margin:0;color:#64748b;font-size:11px}.document-heading h1{margin:5px 0;font-family:SimSun,serif}.doc-code{text-align:right}.doc-code small,.doc-code b{display:block}.doc-code b{font-size:18px;margin:4px}.summary-chart-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:18px}.summary-chart-grid>section,.history-section{border:1px solid #dbe3ec;padding:14px}.summary-title{display:flex;justify-content:space-between;align-items:center}.summary-title span{font-size:11px;color:#64748b}.trend-bars{height:205px;display:flex;align-items:flex-end;gap:16px;padding:18px 8px 4px;border-bottom:1px solid #cbd5e1;overflow:auto}.trend-bars article{min-width:52px;height:170px;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:6px}.trend-bars .bar{width:28px;display:flex;align-items:flex-start;justify-content:center;color:#fff;font-size:10px;padding-top:3px}.trend-bars .rating{background:#2563eb}.trend-bars .defect{background:#dc2626}.trend-bars small{font-size:10px;color:#64748b;white-space:nowrap;transform:rotate(-25deg)}.history-section{margin-top:14px}.history-section .el-table{margin-top:12px}@media(max-width:900px){.summary-chart-grid{grid-template-columns:1fr}.document-heading{grid-template-columns:52px 1fr}.doc-code{display:none}}
</style>
