<template>
  <article class="condition-card periodic-card">
    <div class="document-heading"><div class="doc-badge">C</div><div><p>桥梁定期检查 · 多期历史记录</p><h1>桥梁定期检查记录表</h1><span>PERIODIC BRIDGE INSPECTION RECORDS</span></div><div class="doc-code"><small>记录数量</small><b>{{ periods.length }} 份</b><small>按检查日期倒序</small></div></div>
    <el-empty v-if="!periods.length" description="该桥梁暂无定期检查表"/>
    <el-collapse v-else v-model="active" accordion class="period-list"><el-collapse-item v-for="(period,index) in periods" :key="period.periodic_inspection_code" :name="period.periodic_inspection_code"><template #title><div class="period-title"><b>第 {{ periods.length-index }} 期 · {{ period.inspection_date }}</b><span>{{ period.periodic_inspection_code }}</span><el-tag :type="tagType(period.rating_level_name)">{{ period.rating_level_name || period.rating_level_code || '未评定' }}</el-tag></div></template>
      <section class="card-section"><CardTitle code="C-1" title="本期检查基本信息"/><div class="info-grid"><div v-for="item in summary(period)" :key="item[0]"><b>{{ item[0] }}</b><span>{{ item[1] ?? '—' }}</span></div></div></section>
      <section class="card-section"><CardTitle code="C-2" title="本期桥墩/桥桩检查" subtitle="每个具体桥墩分别记录缺损、评分和建议"/><div v-if="pierRows(period).length" class="matrix-scroll"><table class="record-matrix"><thead><tr><th>桥墩编号</th><th>所在位置</th><th>缺损类型</th><th>缺损程度</th><th>评分</th><th>养护建议</th></tr></thead><tbody><tr v-for="row in pierRows(period)" :key="row.component_inspection_id"><td>{{ row.component_serial }}</td><td>{{ row.location_desc||row.defect_location||'—' }}</td><td>{{ row.defect_type||'未见明显缺损' }}</td><td>{{ row.defect_degree_name||'—' }}</td><td>{{ row.score??'—' }}</td><td>{{ row.maintenance_advice||'—' }}</td></tr></tbody></table></div><el-empty v-else description="本期暂无桥墩检查明细"/></section>
      <section class="card-section"><CardTitle code="C-3" title="其他部位和部件检查"/><el-tabs><el-tab-pane v-for="group in otherGroups(period)" :key="group.name" :label="`${group.name} ${group.rows.length}`"><el-table :data="group.rows" border class="card-table"><el-table-column prop="component_serial" label="构件编号" width="110"/><el-table-column prop="component_name" label="部件名称" min-width="150"/><el-table-column prop="defect_type" label="缺损类型" min-width="140"/><el-table-column prop="defect_degree_name" label="缺损程度" width="110"/><el-table-column prop="score" label="评分" width="80"/><el-table-column prop="maintenance_advice" label="养护建议" min-width="220"/></el-table></el-tab-pane></el-tabs></section>
    </el-collapse-item></el-collapse>
  </article>
</template>
<script setup>
import { defineComponent,h,onMounted,ref,watch } from 'vue'
const props=defineProps({periods:{type:Array,default:()=>[]}}),active=ref('')
const CardTitle=defineComponent({props:{code:String,title:String,subtitle:String},setup:p=>()=>h('div',{class:'section-title'},[h('span',p.code),h('div',[h('h3',p.title),p.subtitle?h('p',p.subtitle):null])])})
const summary=x=>[['定期检查编号',x.periodic_inspection_code],['检查日期',x.inspection_date],['上次检查日期',x.last_inspection_date],['天气及温度',x.weather_temperature],['技术状况等级',x.rating_level_name||x.rating_level_code],['全桥清洁状况',x.cleanliness],['预防及修复状况',x.maintenance_status],['下次检查日期',x.next_inspection_date],['记录人',x.recorder],['负责人',x.principal],['状态',x.status],['部件检查数量',x.componentInspections?.length||0]]
const pierRows=period=>(period.componentInspections||[]).filter(x=>x.component_code==='C010'&&x.component_serial?.includes('#'))
function otherGroups(period){const groups=new Map();for(const row of(period.componentInspections||[]).filter(x=>!(x.component_code==='C010'&&x.component_serial?.includes('#')))){const name=row.part_name||'其他';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(row)}return[...groups].map(([name,rows])=>({name,rows}))}
const tagType=level=>String(level).startsWith('1')||String(level).startsWith('2')?'success':String(level).startsWith('3')?'warning':'danger'
function reset(){active.value=props.periods[0]?.periodic_inspection_code||''}onMounted(reset);watch(()=>props.periods,reset)
</script>
<style scoped>
.condition-card{background:#fff;border:1px solid #cbd5e1;border-top:5px solid #c2410c;border-radius:10px;padding:26px 30px;box-shadow:0 14px 36px rgba(15,23,42,.06)}.document-heading{display:grid;grid-template-columns:64px 1fr 210px;align-items:center;padding:4px 0 22px;border-bottom:2px solid #0f172a}.doc-badge{width:52px;height:52px;display:grid;place-items:center;background:#c2410c;color:#fff;font:700 26px Georgia;border-radius:8px}.document-heading p,.document-heading span{margin:0;color:#64748b;font-size:11px}.document-heading h1{font-family:SimSun,serif;margin:5px 0;font-size:28px}.doc-code{text-align:right}.doc-code small,.doc-code b{display:block}.doc-code b{font-size:18px;margin:4px}.period-list{margin-top:20px}.period-title{display:flex;align-items:center;gap:14px;width:100%;padding-right:18px}.period-title span{color:#64748b;font-size:12px}.period-title .el-tag{margin-left:auto}.card-section{margin:18px 0;border:1px solid #d4dde7;border-radius:8px;overflow:hidden}.section-title{display:flex;align-items:center;gap:12px;padding:13px 16px;background:linear-gradient(90deg,#c2410c,#9a3412);color:#fff}.section-title>span{background:#fff;color:#c2410c;padding:6px 8px;border-radius:5px;font-weight:800}.section-title h3,.section-title p{margin:0}.section-title p{font-size:11px;color:#ffedd5;margin-top:3px}.info-grid{display:grid;grid-template-columns:repeat(3,1fr)}.info-grid>div{display:grid;grid-template-columns:140px 1fr;border-right:1px solid #d4dde7;border-bottom:1px solid #d4dde7}.info-grid b,.info-grid span{padding:12px}.info-grid b{background:#fff7ed}.matrix-scroll{overflow:auto}.record-matrix{width:100%;min-width:850px;border-collapse:collapse}.record-matrix th,.record-matrix td{border:1px solid #cbd5e1;padding:10px;text-align:center}.record-matrix th{background:#c2410c;color:#fff}.card-table{--el-table-header-bg-color:#fff7ed}@media(max-width:800px){.info-grid{grid-template-columns:1fr}.document-heading{grid-template-columns:55px 1fr}.doc-code{display:none}.period-title{flex-wrap:wrap}.period-title .el-tag{margin-left:0}}
</style>