<template>
  <article class="condition-card inspection-card">
    <div class="document-heading"><div class="doc-badge blue">B</div><div><p>桥梁初始检查 · 唯一基准记录</p><h1>桥梁初始检查记录表</h1><span>INITIAL BRIDGE INSPECTION RECORD</span></div><div class="doc-code"><small>初始检查编号</small><b>{{ record?.initial_inspection_code || '未建立' }}</b><small>检查日期 {{ record?.inspection_date || '—' }}</small></div></div>
    <template v-if="record">
      <section class="card-section"><CardTitle code="B-1" title="初始检查基本信息"/><div class="info-grid"><div v-for="item in summary" :key="item[0]"><b>{{ item[0] }}</b><span>{{ item[1] || '—' }}</span></div></div></section>
      <section class="card-section"><CardTitle code="B-2" title="全桥通用检测项目"/><el-table :data="items" border class="card-table"><el-table-column prop="item_category" label="项目分类" width="150"/><el-table-column prop="item_name" label="检测项目" min-width="190"/><el-table-column prop="measured_value" label="检测结果" min-width="180"/><el-table-column prop="unit" label="单位" width="90"/><el-table-column prop="inspection_description" label="检测说明" min-width="200"/></el-table></section>
      <section class="card-section"><CardTitle code="B-3" title="按桥墩/桥桩分类检测" subtitle="同一张初始检查表内，每个桥墩分别记录"/><div v-if="matrix.columns.length" class="matrix-scroll"><table class="record-matrix"><thead><tr><th>检测项目</th><th v-for="pier in matrix.columns" :key="pier">{{ pier }}</th></tr></thead><tbody><tr v-for="row in matrix.rows" :key="row.name"><td>{{ row.name }}</td><td v-for="pier in matrix.columns" :key="pier">{{ row.values[pier] || '—' }}</td></tr></tbody></table></div><el-empty v-else description="暂无桥墩分类初检记录"/></section>
    </template><el-empty v-else description="该桥梁尚未建立初始检查记录表"/>
  </article>
</template>
<script setup>
import { computed,defineComponent,h } from 'vue'
const props=defineProps({record:Object,items:{type:Array,default:()=>[]},componentItems:{type:Array,default:()=>[]}})
const CardTitle=defineComponent({props:{code:String,title:String,subtitle:String},setup:p=>()=>h('div',{class:'section-title'},[h('span',p.code),h('div',[h('h3',p.title),p.subtitle?h('p',p.subtitle):null])])})
const summary=computed(()=>{const x=props.record||{};return[['检查日期',x.inspection_date],['检查机构',x.inspection_org],['检查人员',x.inspectors],['桥梁工程师',x.bridge_engineer],['天气及温度',x.weather_temperature],['主跨结构',x.main_span_structure],['最大跨径（m）',x.maximum_span],['结构形式',x.structure_form],['施工方法',x.construction_method],['病害描述及建议',x.defect_advice],['记录状态',x.status],['初始检查编号',x.initial_inspection_code]]})
const matrix=computed(()=>{const columns=[...new Set(props.componentItems.map(x=>x.component_serial))];const rows=new Map();for(const item of props.componentItems){const name=item.item_name||item.item_code;if(!rows.has(name))rows.set(name,{name,values:{}});rows.get(name).values[item.component_serial]=item.measured_value}return{columns,rows:[...rows.values()]}})
</script>
<style scoped>
.condition-card{background:#fff;border:1px solid #cbd5e1;border-top:5px solid #1d4ed8;border-radius:10px;padding:26px 30px;box-shadow:0 14px 36px rgba(15,23,42,.06)}.document-heading{display:grid;grid-template-columns:64px 1fr 210px;align-items:center;padding:4px 0 22px;border-bottom:2px solid #0f172a}.doc-badge{width:52px;height:52px;display:grid;place-items:center;background:#1d4ed8;color:#fff;font:700 26px Georgia;border-radius:8px}.document-heading p,.document-heading span{margin:0;color:#64748b;font-size:11px;letter-spacing:1.2px}.document-heading h1{font-family:SimSun,serif;margin:5px 0;font-size:28px}.doc-code{text-align:right}.doc-code small,.doc-code b{display:block}.doc-code b{font-size:18px;margin:4px 0}.card-section{margin-top:22px;border:1px solid #d4dde7;border-radius:8px;overflow:hidden}.section-title{display:flex;align-items:center;gap:12px;padding:13px 16px;background:linear-gradient(90deg,#1d4ed8,#1e40af);color:#fff}.section-title>span{background:#fff;color:#1d4ed8;padding:6px 8px;border-radius:5px;font-weight:800}.section-title h3,.section-title p{margin:0}.section-title p{font-size:11px;color:#dbeafe;margin-top:3px}.info-grid{display:grid;grid-template-columns:repeat(3,1fr)}.info-grid>div{display:grid;grid-template-columns:140px 1fr;border-right:1px solid #d4dde7;border-bottom:1px solid #d4dde7;min-height:52px}.info-grid b,.info-grid span{padding:12px}.info-grid b{background:#f8fafc}.card-table{--el-table-header-bg-color:#eff6ff}.matrix-scroll{overflow:auto}.record-matrix{width:100%;min-width:750px;border-collapse:collapse}.record-matrix th,.record-matrix td{border:1px solid #cbd5e1;padding:11px;text-align:center;white-space:nowrap}.record-matrix th{background:#1d4ed8;color:#fff}.record-matrix th:first-child,.record-matrix td:first-child{position:sticky;left:0;background:#eff6ff;color:#1e3a8a;font-weight:700}@media(max-width:800px){.info-grid{grid-template-columns:1fr}.document-heading{grid-template-columns:55px 1fr}.doc-code{display:none}}
</style>