<template>
  <article class="official-record periodic-record">
    <div class="record-title"><h1>{{ template.title }}</h1><span>{{ template.subtitle }} · 表 {{ template.code }}</span></div>
    <div class="record-filter no-print"><span>检查时间</span><el-date-picker v-model="dateRange" type="daterange" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" value-format="YYYY-MM-DD" clearable/><b>共 {{ filteredPeriods.length }} 份</b></div>
    <el-empty v-if="!filteredPeriods.length" description="当前时间范围内没有定期检查表"/>
    <section v-for="period in filteredPeriods" :key="period.periodic_inspection_code" class="period-page">
      <div class="page-caption">公路管理机构名称：{{ bridge?.road_management_org || '未录入' }}<strong>{{ template.title }}</strong></div>
      <table class="official-table top-table"><tbody><tr v-for="row in topRows(period)" :key="row[0].no"><template v-for="field in row" :key="field.no"><th>{{ field.no }} {{ field.label }}</th><td>{{ field.value }}</td></template></tr></tbody></table>
      <table class="official-table defect-table"><thead><tr><th>序号</th><th>16 部位</th><th>17 部件名称</th><th>18 评分</th><th colspan="5">19 缺损</th><th>20 养护建议（维修范围、方式、时间）</th><th>21 是否需特殊检查</th></tr><tr><th></th><th></th><th></th><th></th><th>类型</th><th>位置</th><th>范围</th><th>照片</th><th>最不利构件</th><th></th><th></th></tr></thead><tbody><tr v-for="(item,index) in componentRows(period)" :key="`${period.periodic_inspection_code}-${item.name}`"><td>{{ index+1 }}</td><td>{{ item.part }}</td><td>{{ item.name }}</td><td>{{ item.row?.score ?? '未录入' }}</td><td>{{ item.row?.defect_type || '未录入' }}</td><td>{{ item.row?.defect_location || item.row?.location_desc || '未录入' }}</td><td>{{ item.row?.defect_scope || '未录入' }}</td><td>{{ item.row?.photo_count ? `${item.row.photo_count}张` : '未录入' }}</td><td>{{ item.row?.unfavorable_component || item.row?.component_serial || '未录入' }}</td><td>{{ item.row?.maintenance_advice || '未录入' }}</td><td>{{ item.row?.special_inspection_required || '否' }}</td></tr></tbody></table>
      <table class="official-table footer-table"><tbody><tr><th>22 桥梁技术状况评定等级</th><td>{{ period.rating_level_name || period.rating_level_code || '未评定' }}</td><th>23 全桥清洁状况</th><td>{{ period.cleanliness || '未录入' }}</td><th>24 预防及修复养护状况</th><td>{{ period.maintenance_status || '未录入' }}</td></tr><tr><th>25 记录人</th><td>{{ period.recorder || '未录入' }}</td><th>26 负责人</th><td>{{ period.principal || '未录入' }}</td><th>27 下次检查时间</th><td>{{ period.next_inspection_date || '未录入' }}</td></tr></tbody></table>
    </section>
  </article>
</template>

<script setup>
import { computed, ref } from 'vue'

const props=defineProps({bridge:Object,periods:{type:Array,default:()=>[]}})
const dateRange=ref([])
const templates={beam:{code:'C-1',title:'桥梁定期检查记录表（梁桥）',subtitle:'梁桥'},arch:{code:'C-2',title:'桥梁定期检查记录表（拱桥）',subtitle:'板拱桥、肋拱桥、箱形拱桥、双曲拱桥'},rigid_arch:{code:'C-3',title:'桥梁定期检查记录表（刚架拱桥）',subtitle:'刚架拱桥'},composite_arch:{code:'C-4',title:'桥梁定期检查记录表（钢-混凝土组合拱桥）',subtitle:'钢-混凝土组合拱桥'},cable_stayed:{code:'C-5',title:'桥梁定期检查记录表（斜拉桥）',subtitle:'斜拉桥'},suspension:{code:'C-6',title:'桥梁定期检查记录表（悬索桥）',subtitle:'悬索桥'}}
const template=computed(()=>templates[props.bridge?.bridge_type_code]||{code:'C',title:'桥梁定期检查记录表',subtitle:'桥型待核验'})
const common=['桥面铺装','伸缩装置','排水系统','人行道','栏杆、护栏','照明、标志','桥路连接处']
const byType={beam:['主要承重构件','横向联系','桥面板','桥墩及基础','桥台及基础','翼墙、耳墙','锥坡、护坡'],arch:['主拱','拱上结构','桥面板','桥墩及基础','桥台及基础','翼墙、耳墙','锥坡、护坡'],rigid_arch:['拼片','横向联系','桥面板','桥墩及基础','桥台及基础','翼墙、耳墙','锥坡、护坡'],composite_arch:['拱肋','横向联系','吊杆','立柱','系杆','桥面板','支座','桥墩及基础','桥台及基础','翼墙、耳墙','锥坡、护坡'],cable_stayed:['主梁','斜拉索系统（斜拉索、锚具、拉索减震装置等）','索塔','支座','桥墩及基础','桥台及基础','翼墙、耳墙','锥坡、护坡'],suspension:['加劲梁','索塔','主缆','索鞍','索夹','吊杆系统（吊杆、锚具、吊杆减震装置等）','锚碇','墩台及基础','散索鞍','锚杆','桥台及基础','翼墙、耳墙','锥坡、护坡']}
const accessory=['防撞设施','防雷设施','防抛网、声屏障','检修设施','监测系统、永久观测点','调治构造物','其他']
const filteredPeriods=computed(()=>props.periods.filter(row=>{if(!dateRange.value?.length)return true;const date=String(row.inspection_date||'');return date>=dateRange.value[0]&&date<=dateRange.value[1]}).sort((a,b)=>String(b.inspection_date||'').localeCompare(String(a.inspection_date||''))))
const show=value=>value===null||value===undefined||value===''?'未录入':String(value)
function topRows(period){const b=props.bridge||{};const values=[['路线编号',b.route_code],['路线名称',b.route_name],['桥位桩号',b.pile_number],['桥梁编号',b.bridge_code],['桥梁名称',b.bridge_name],['被跨越道路名称',b.crossed_road_name],['桥梁全长(m)',b.bridge_length],['主跨结构',period.main_span_structure||b.structural_system],['最大跨径(m)',period.maximum_span],['管养单位',b.management_unit],['建成时间',b.completion_date||b.built_year],['上次修复养护时间',period.last_maintenance_date],['上次检查时间',period.last_inspection_date],['本次检查时间',period.inspection_date],['本次检查时气候及环境温度',period.weather_temperature]];return[values.slice(0,3),values.slice(3,6),values.slice(6,9),values.slice(9,12),values.slice(12,15)].map((row,rowIndex)=>row.map((entry,index)=>({no:rowIndex*3+index+1,label:entry[0],value:show(entry[1])})))}
function componentRows(period){const labels=[...common,...(byType[props.bridge?.bridge_type_code]||[]),...accessory];return labels.map(name=>({name,part:common.includes(name)?'桥面系':accessory.includes(name)?'附属设施':byType[props.bridge?.bridge_type_code]?.includes(name)&&['桥墩及基础','桥台及基础','翼墙、耳墙','锥坡、护坡','墩台及基础','散索鞍','锚杆'].includes(name)?'下部结构':'上部结构',row:(period.componentInspections||[]).find(item=>String(item.component_name||'').includes(name)||name.includes(String(item.component_name||'')))}))}
</script>

<style scoped>
.official-record{background:#fff;color:#111;font-family:SimSun,serif}.record-title{text-align:center;border-top:2px solid #111;border-bottom:1px solid #111;padding:7px}.record-title h1,.record-title span{margin:0}.record-title h1{font-size:23px}.record-title span{font-size:12px;color:#475569}.record-filter{display:flex;align-items:center;gap:10px;padding:14px 0;font-family:system-ui,sans-serif}.record-filter b{font-size:13px;color:#475569}.period-page{margin-top:16px;break-inside:avoid}.page-caption{font-weight:700;border-top:2px solid #111;padding:5px 0}.page-caption strong{display:block;text-align:center;font-size:18px}.official-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:12px}.official-table th,.official-table td{border:1px solid #111;padding:4px;vertical-align:middle;word-break:break-word}.official-table th{background:#fafafa;text-align:center}.top-table th{width:10%}.top-table td{width:23.3%;height:27px}.defect-table{margin-top:10px}.defect-table th:nth-child(1){width:3%}.defect-table th:nth-child(2){width:5%}.defect-table th:nth-child(3){width:8%}.defect-table th:nth-child(4){width:4%}.defect-table th:nth-child(5),.defect-table th:nth-child(6),.defect-table th:nth-child(7),.defect-table th:nth-child(8),.defect-table th:nth-child(9){width:6%}.defect-table th:nth-child(10){width:13%}.defect-table th:nth-child(11){width:7%}.defect-table td{height:28px;text-align:center}.footer-table th{width:12%}.footer-table td{width:21.3%;height:29px}.footer-table{margin-top:-1px}@media print{.no-print{display:none!important}.period-page{break-before:page}.period-page:first-of-type{break-before:auto}}@media(max-width:900px){.defect-table{font-size:10px}.official-table th,.official-table td{padding:3px}.record-filter{align-items:flex-start;flex-direction:column}}
</style>
