<template>
  <section class="bridge-edit-page">
    <div class="edit-heading"><div><span>桥梁档案</span><h2>{{ editing?'编辑桥梁基础状况':'新增桥梁基础状况' }}</h2></div><div><el-button @click="router.back()">取消</el-button><el-button type="primary" :loading="saving" @click="save"><Save :size="16"/>保存档案</el-button></div></div>
    <el-form label-position="top">
      <EditSection code="A" title="桥梁所处行政区划" subtitle="位置和坐标信息"><div class="form-grid"><Field v-for="item in areaFields" :key="item.key" :item="item"/></div></EditSection>
      <EditSection code="B" title="行政识别数据" subtitle="路线、桥梁身份及建设单位"><div class="form-grid"><el-form-item label="桥梁编号" required><el-input v-model="form.bridge_code" :disabled="editing"/></el-form-item><el-form-item label="桥梁名称" required><el-input v-model="form.bridge_name"/></el-form-item><el-form-item label="路线"><el-select v-model="form.route_code" filterable style="width:100%"><el-option v-for="item in routes" :key="item.route_code" :label="`${item.route_code} · ${item.route_name}`" :value="item.route_code"/></el-select></el-form-item><el-form-item label="桥梁类型"><el-select v-model="form.bridge_type_code" filterable style="width:100%"><el-option v-for="item in bridgeTypes" :key="item.bridge_type_code" :label="item.bridge_type_name" :value="item.bridge_type_code"/></el-select></el-form-item><Field v-for="item in identityFields" :key="item.key" :item="item"/></div></EditSection>
      <EditSection code="C" title="桥梁技术指标" subtitle="桥面、净空、引道和水文指标"><div class="form-grid"><Field v-for="item in technicalFields" :key="item.key" :item="item"/></div></EditSection>
      <EditSection code="D" title="桥梁结构信息" subtitle="数量决定表格列数，明细可逐行维护">
        <DetailTitle title="桥梁分孔" button="增加一孔" @add="addSpan"/><el-table :data="structures.spans" border><el-table-column label="孔号" width="100"><template #default="{row}"><el-input-number v-model="row.span_no" :min="1" controls-position="right"/></template></el-table-column><el-table-column label="跨径（m）"><template #default="{row}"><el-input v-model="row.span_length"/></template></el-table-column><el-table-column label="结构形式"><template #default="{row}"><el-input v-model="row.structure_form"/></template></el-table-column><el-table-column label="材料"><template #default="{row}"><el-input v-model="row.material_type"/></template></el-table-column><RemoveColumn @remove="index=>structures.spans.splice(index,1)"/></el-table>
        <DetailTitle title="结构体系、上下部结构与附属设施" button="增加结构明细" @add="addStructure"/><el-table :data="structures.structures" border><el-table-column label="分组" width="150"><template #default="{row}"><el-select v-model="row.structure_group"><el-option v-for="item in structureGroups" :key="item.value" :label="item.label" :value="item.value"/></el-select></template></el-table-column><el-table-column label="结构类型" width="160"><template #default="{row}"><el-input v-model="row.structure_type"/></template></el-table-column><el-table-column label="序号" width="100"><template #default="{row}"><el-input v-model="row.serial_no"/></template></el-table-column><el-table-column label="形式"><template #default="{row}"><el-input v-model="row.form"/></template></el-table-column><el-table-column label="材料"><template #default="{row}"><el-input v-model="row.material_type"/></template></el-table-column><el-table-column label="数量" width="100"><template #default="{row}"><el-input v-model="row.quantity"/></template></el-table-column><RemoveColumn @remove="index=>structures.structures.splice(index,1)"/></el-table>
        <DetailTitle title="斜拉索、吊杆、系杆（含索力）" button="增加索" @add="addCable"/><el-table :data="structures.cables" border><el-table-column label="索类型" width="140"><template #default="{row}"><el-select v-model="row.cable_type"><el-option v-for="item in cableTypes" :key="item" :label="item" :value="item"/></el-select></template></el-table-column><el-table-column label="编号" width="110"><template #default="{row}"><el-input v-model="row.serial_no"/></template></el-table-column><el-table-column label="索力"><template #default="{row}"><el-input v-model="row.force_value"/></template></el-table-column><el-table-column label="材料"><template #default="{row}"><el-input v-model="row.material_type"/></template></el-table-column><el-table-column label="位置"><template #default="{row}"><el-input v-model="row.location_desc"/></template></el-table-column><RemoveColumn @remove="index=>structures.cables.splice(index,1)"/></el-table>
      </EditSection>
      <EditSection code="E" title="补充说明" subtitle="建档人和备注"><div class="form-grid"><Field v-for="item in extraFields" :key="item.key" :item="item"/><el-form-item label="需要说明的事项" class="full-row"><el-input v-model="form.notes" type="textarea" :rows="3"/></el-form-item></div></EditSection>
    </el-form>
  </section>
</template>
<script setup>
import { defineComponent, h, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElButton, ElFormItem, ElInput, ElMessage, ElTableColumn } from 'element-plus'
import { Plus, Save } from 'lucide-vue-next'
import http from '../api/http'
const route=useRoute(),router=useRouter(),editing=ref(Boolean(route.params.bridgeCode)),saving=ref(false),routes=ref([]),bridgeTypes=ref([]),form=reactive({}),structures=reactive({spans:[],structures:[],cables:[]})
const make=items=>items.map(([key,label])=>({key,label})),areaFields=make([['administrative_code','行政区划代码'],['location_address','桥梁详细地址'],['longitude','经度（WGS-84）'],['latitude','纬度（WGS-84）']]),identityFields=make([['pile_number','桥位桩号'],['function_type','功能类型'],['maintenance_level','养护检查等级'],['built_year','建成年份'],['design_load','设计荷载'],['design_unit','设计单位'],['construction_unit','施工单位'],['supervision_unit','监理单位'],['owner_unit','业主单位'],['management_unit','管养单位'],['road_management_org','公路管理机构']]),technicalFields=make([['bridge_length','桥梁全长（m）'],['deck_width','桥面总宽（m）'],['lane_width','车道宽度（m）'],['sidewalk_width','人行道宽度（m）'],['barrier_height','护栏或防撞墙高度（m）'],['median_width','中央分隔带宽度（m）'],['standard_clearance','桥面标准净空'],['actual_clearance','桥面实际净空'],['navigation_standard','桥下通航等级及标准净空'],['navigation_actual','桥下实际净空'],['approach_width','引道总宽（m）'],['approach_alignment','引道线形或曲线半径'],['design_flood','设计洪水频率及水位'],['historical_flood','历史洪水位'],['seismic_coefficient','地震动峰值加速度系数']]),extraFields=make([['structural_system','结构体系'],['span_combination','桥梁分联及跨径组合'],['bridge_engineer','桥梁工程师'],['card_filler','填卡人'],['card_date','填卡日期']])
const structureGroups=[{value:'system',label:'结构体系'},{value:'superstructure',label:'上部结构'},{value:'deck',label:'桥面系'},{value:'substructure',label:'下部结构'},{value:'foundation',label:'基础形式'},{value:'bearing',label:'支座形式'},{value:'accessory',label:'附属设施'}],cableTypes=['斜拉索','吊杆','系杆']
const EditSection=defineComponent({props:{code:String,title:String,subtitle:String},setup:(p,{slots})=>()=>h('section',{class:'edit-section'},[h('div',{class:'section-head'},[h('b',p.code),h('div',[h('h3',p.title),h('span',p.subtitle)])]),slots.default?.()])}),Field=defineComponent({props:{item:Object},setup:p=>()=>h(ElFormItem,{label:p.item.label},()=>h(ElInput,{modelValue:form[p.item.key],onInput:value=>form[p.item.key]=value}))}),DetailTitle=defineComponent({emits:['add'],props:{title:String,button:String},setup:(p,{emit})=>()=>h('div',{class:'detail-toolbar'},[h('strong',p.title),h(ElButton,{size:'small',onClick:()=>emit('add')},()=>[h(Plus,{size:14}),p.button])])}),RemoveColumn=defineComponent({emits:['remove'],setup:(_,{emit})=>()=>h(ElTableColumn,{label:'操作',width:80},{default:scope=>h(ElButton,{text:true,type:'danger',onClick:()=>emit('remove',scope.$index)},()=> '删除')})})
function addSpan(){structures.spans.push({span_no:structures.spans.length+1,span_length:'',structure_form:'',material_type:''})}function addStructure(){structures.structures.push({structure_group:'superstructure',structure_type:'',serial_no:String(structures.structures.length+1),form:'',material_type:'',quantity:1})}function addCable(){structures.cables.push({cable_type:'斜拉索',serial_no:String(structures.cables.length+1),force_value:'',material_type:'',location_desc:''})}
async function load(){const [routeData,typeData]=await Promise.all([http.get('/routes',{params:{size:100}}),http.get('/bridge-types',{params:{size:100}})]);routes.value=routeData.records;bridgeTypes.value=typeData.records;if(editing.value){Object.assign(form,await http.get(`/bridges/${route.params.bridgeCode}`));Object.assign(structures,await http.get(`/bridge-profiles/${route.params.bridgeCode}/structures`))}}
async function save(){if(!form.bridge_code||!form.bridge_name||!form.route_code||!form.bridge_type_code){ElMessage.warning('请填写桥梁编号、名称、路线和桥梁类型');return}saving.value=true;try{let code=form.bridge_code;if(editing.value)await http.put(`/bridges/${route.params.bridgeCode}`,form);else code=(await http.post('/bridges',form)).bridge_code;await http.put(`/bridge-profiles/${code}/structures`,structures);ElMessage.success('桥梁档案保存成功');router.push(`/bridges/${code}`)}finally{saving.value=false}}
onMounted(load)
</script>
<style scoped>
.bridge-edit-page{max-width:1500px;margin:auto}.edit-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.edit-heading span{color:#0f766e;font-size:12px;font-weight:700}.edit-heading h2{margin:5px 0 0}.edit-heading>div:last-child{display:flex;gap:8px}.edit-heading .el-button{display:flex;gap:6px}.edit-section{background:#fff;border:1px solid #dbe3ec;border-radius:8px;margin-bottom:14px;overflow:hidden}.section-head{display:flex;align-items:center;gap:12px;padding:14px 18px;background:#f8fafc;border-bottom:1px solid #dbe3ec}.section-head>b{display:grid;place-items:center;width:34px;height:34px;background:#0f766e;color:#fff;border-radius:6px}.section-head h3{margin:0;font-size:16px}.section-head span{color:#64748b;font-size:11px}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px 16px;padding:18px}.full-row{grid-column:1/-1}.detail-toolbar{display:flex;align-items:center;justify-content:space-between;padding:14px 18px 10px}.detail-toolbar .el-button{display:flex;gap:4px}@media(max-width:1050px){.form-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.form-grid{grid-template-columns:1fr}.full-row{grid-column:auto}.edit-heading{align-items:flex-start;flex-direction:column;gap:12px}}
</style>
