<template>
  <section class="record-page table-panel">
    <div class="record-heading"><div><span>{{ isInitial?'表 B · 初始检查':'表 C · 定期检查' }}</span><h2>{{ isInitial?'桥梁初始检查记录':'桥梁定期检查记录' }}</h2><p>{{ isInitial?'检查记录通过任务工作台填写，此处仅供查看。':'检查记录通过任务工作台填写，此处仅供查看。' }}</p></div></div>
    <div class="record-filters"><el-input v-model="filters.keyword" clearable placeholder="检查编号、桥梁编号或人员" @keyup.enter="load"/><el-input v-model="filters.bridge_code" clearable placeholder="桥梁编号" @keyup.enter="load"/><el-button @click="load">查询</el-button></div>
    <el-table :data="rows" border height="580">
      <template v-if="isInitial">
        <el-table-column prop="initial_inspection_code" label="初始检查编号" width="175"/><el-table-column prop="task_id" label="任务编号" width="150"/><el-table-column prop="bridge_code" label="桥梁编号" width="125"/><el-table-column prop="bridge_name" label="桥梁名称" min-width="170"/><el-table-column prop="inspection_date" label="检查日期" width="120"/><el-table-column prop="inspection_org" label="检查机构" min-width="160"/><el-table-column prop="inspectors" label="检查人员" min-width="140"/>
      </template>
      <template v-else>
        <el-table-column prop="periodic_inspection_code" label="定期检查编号" width="175"/><el-table-column prop="task_id" label="任务编号" width="150"/><el-table-column prop="form_table_code" label="定检表号" width="90"/><el-table-column prop="bridge_code" label="桥梁编号" width="125"/><el-table-column prop="bridge_name" label="桥梁名称" min-width="170"/><el-table-column prop="inspection_date" label="检查日期" width="120"/><el-table-column prop="rating_level_code" label="技术状况等级" width="120"/><el-table-column prop="recorder" label="记录人" width="120"/>
      </template>
      <el-table-column prop="status" label="记录状态" width="105"><template #default="{row}">{{ statusName(row.status) }}</template></el-table-column>
      <el-table-column prop="task_status" label="任务状态" width="105"><template #default="{row}"><el-tag :type="isLocked(row)?'info':'success'" size="small">{{ row.task_status||'未关联' }}</el-tag></template></el-table-column>
      <el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button text type="primary" @click="viewRecord(row)">查看</el-button><el-popconfirm v-if="canDelete&&!isLocked(row)" title="确认删除这份检查记录？" @confirm="remove(row)"><template #reference><el-button text type="danger">删除</el-button></template></el-popconfirm><span v-if="isLocked(row)" class="locked-text">已完成，禁止修改</span></template></el-table-column>
    </el-table>
    <div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="size" layout="total, sizes, prev, pager, next" :total="total" :page-sizes="[10,20,50]" @change="load"/></div>

    <el-drawer v-model="drawer" title="查看检查记录" size="780px">
      <el-form label-position="top" class="form-grid">
        <template v-if="isInitial"><el-form-item label="初始检查编号"><el-input :model-value="form.initial_inspection_code" disabled/></el-form-item><el-form-item label="桥梁编号"><el-input :model-value="form.bridge_code" disabled/></el-form-item><el-form-item label="检查日期"><el-input :model-value="form.inspection_date" disabled/></el-form-item><el-form-item label="下次定期检查日期"><el-input :model-value="form.next_inspection_date||'—'" disabled/></el-form-item><el-form-item label="检查机构"><el-input :model-value="form.inspection_org||'—'" disabled/></el-form-item><el-form-item label="检查人员"><el-input :model-value="form.inspectors||'—'" disabled/></el-form-item><el-form-item label="桥梁工程师"><el-input :model-value="form.bridge_engineer||'—'" disabled/></el-form-item><el-form-item label="天气与环境温度"><el-input :model-value="form.weather_temperature||'—'" disabled/></el-form-item><el-form-item label="主跨结构"><el-input :model-value="form.main_span_structure||'—'" disabled/></el-form-item><el-form-item label="最大跨径（m）"><el-input :model-value="form.maximum_span||'—'" disabled/></el-form-item><el-form-item label="结构形式"><el-input :model-value="form.structure_form||'—'" disabled/></el-form-item><el-form-item label="施工方法"><el-input :model-value="form.construction_method||'—'" disabled/></el-form-item><el-form-item label="施工返工情况"><el-input :model-value="form.construction_rework||'—'" disabled/></el-form-item><el-form-item label="加固改造情况"><el-input :model-value="form.reinforcement_info||'—'" disabled/></el-form-item><el-form-item label="档案缺图情况"><el-input :model-value="form.missing_archive_drawings||'—'" disabled/></el-form-item><el-form-item label="病害描述与建议" class="full-row"><el-input :model-value="form.defect_advice||'—'" disabled type="textarea" :rows="2"/></el-form-item></template>
        <template v-else><el-form-item label="定期检查编号"><el-input :model-value="form.periodic_inspection_code" disabled/></el-form-item><el-form-item label="桥梁编号"><el-input :model-value="form.bridge_code" disabled/></el-form-item><el-form-item label="检查日期"><el-input :model-value="form.inspection_date" disabled/></el-form-item><el-form-item label="上次检查日期"><el-input :model-value="form.last_inspection_date||'—'" disabled/></el-form-item><el-form-item label="技术状况等级"><el-input :model-value="form.rating_level_code||'—'" disabled/></el-form-item><el-form-item label="下次检查日期"><el-input :model-value="form.next_inspection_date||'—'" disabled/></el-form-item><el-form-item label="天气与环境温度"><el-input :model-value="form.weather_temperature||'—'" disabled/></el-form-item><el-form-item label="全桥清洁状况"><el-input :model-value="form.cleanliness||'—'" disabled/></el-form-item><el-form-item label="预防及修复状况"><el-input :model-value="form.maintenance_status||'—'" disabled/></el-form-item><el-form-item label="记录人"><el-input :model-value="form.recorder||'—'" disabled/></el-form-item><el-form-item label="负责人"><el-input :model-value="form.principal||'—'" disabled/></el-form-item></template>
      </el-form>
      <div v-if="inspectionItems.length" style="margin-top:16px"><strong style="color:#0f766e;font-size:14px">{{ isInitial?'检查项目清单':'部件检查记录' }}</strong><el-table :data="inspectionItems" border size="small" style="margin-top:8px"><template v-if="isInitial"><el-table-column prop="item_name" label="项目名称" min-width="160"/><el-table-column prop="measured_value" label="实测值" width="120"/><el-table-column prop="unit" label="单位" width="80"/><el-table-column prop="inspection_description" label="检查描述" min-width="200"/></template><template v-else><el-table-column prop="part_name" label="部位" width="100"/><el-table-column prop="component_name" label="部件" width="120"/><el-table-column prop="defect_type" label="缺损类型" min-width="120"/><el-table-column prop="defect_location" label="缺损位置" width="120"/><el-table-column prop="defect_range" label="缺损范围" width="100"/><el-table-column prop="score" label="评分" width="80"/><el-table-column prop="maintenance_advice" label="养护建议" min-width="140"/><el-table-column prop="defect_degree_name" label="缺损程度" width="100"/></template></el-table></div>
    </el-drawer>
  </section>
</template>
<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import http from '../api/http'
import { useAuthStore } from '../stores/auth'
const props=defineProps({inspectionType:{type:String,default:'initial'}}),route=useRoute(),router=useRouter(),auth=useAuthStore(),isInitial=computed(()=>props.inspectionType==='initial'),resource=computed(()=>isInitial.value?'initial-inspections':'periodic-inspections'),idField=computed(()=>isInitial.value?'initial_inspection_code':'periodic_inspection_code'),canDelete=computed(()=>auth.role==='admin'),rows=ref([]),total=ref(0),page=ref(1),size=ref(10),drawer=ref(false),form=reactive({}),filters=reactive({keyword:'',bridge_code:''}),inspectionItems=ref([])
const ratingLevels=[1,2,3,4,5].map(value=>({value:String(value),label:`${value} 类`}))
function statusName(value){return {draft:'草稿',pending:'待审核',approved:'已审核',completed:'已完成',archived:'已归档'}[value]||value||'未填写'}
function isLocked(row){return ['已完成','已审核','已取消'].includes(row.task_status)}
async function load(){const data=await http.get(`/${resource.value}`,{params:{page:page.value,size:size.value,keyword:filters.keyword,bridge_code:filters.bridge_code}});rows.value=data.records;total.value=data.total}
async function viewRecord(row){Object.keys(form).forEach(key=>delete form[key]);Object.assign(form,row);drawer.value=true;inspectionItems.value=[];try{if(isInitial.value){const data=await http.get('/initial-inspection-items',{params:{initial_inspection_code:row.initial_inspection_code,size:200}});const items=data.records||[];const defs=await http.get('/initial-item-definitions',{params:{size:200}});const defMap={};(defs.records||[]).forEach(d=>{defMap[d.item_code]=d});inspectionItems.value=items.map(i=>({...i,item_name:(defMap[i.item_code]||{}).item_name||i.item_code,unit:(defMap[i.item_code]||{}).unit||''}))}else{const [compData,partData,compDefData]=await Promise.all([http.get('/component-inspection-records',{params:{periodic_inspection_code:row.periodic_inspection_code,size:500}}),http.get('/bridge-positions',{params:{size:50}}),http.get('/bridge-components',{params:{size:100}})]);const partMap={},compMap={},degrees={slight:'轻微',medium:'中等',serious:'严重',danger:'危险'};(partData.records||[]).forEach(p=>{partMap[p.part_code]=p.part_name});(compData.records||[]).forEach(c=>{compMap[c.component_code]=c.component_name});inspectionItems.value=(compData.records||[]).map(r=>({...r,part_name:partMap[r.part_code]||r.part_code,component_name:compMap[r.component_code]||r.component_code,defect_degree_name:degrees[r.defect_degree_code]||r.defect_degree_code||''}))}}catch{inspectionItems.value=[]}}
async function remove(row){await http.delete(`/${resource.value}/${row[idField.value]}`);ElMessage.success('检查记录已删除');await load()}
onMounted(load);watch([()=>props.inspectionType,()=>route.path],()=>{page.value=1;load()})
</script>
<style scoped>
.record-page{max-width:1600px;margin:auto}.record-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.record-heading span{color:#0f766e;font-size:12px;font-weight:700}.record-heading h2{margin:6px 0;font-size:24px}.record-heading p{margin:0;color:#64748b}.record-filters{display:flex;gap:10px;margin-bottom:14px}.record-filters .el-input{max-width:290px}.pager{display:flex;justify-content:flex-end;margin-top:14px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px 16px}.locked-text{font-size:12px;color:#94a3b8}@media(max-width:700px){.record-heading{align-items:flex-start;flex-direction:column;gap:12px}.record-filters{flex-direction:column}.record-filters .el-input{max-width:none}.form-grid{grid-template-columns:1fr}}
</style>
