<template>
  <section class="table-panel route-page">
    <div class="resource-heading"><div><span>基础数据</span><h2>路线管理</h2></div><el-button type="primary" @click="openCreate"><Plus :size="16"/>新增路线</el-button></div>
    <div class="toolbar"><div class="toolbar-left"><el-input v-model="keyword" clearable placeholder="路线编号或路线名称" style="width:280px" @keyup.enter="load"/><el-button @click="load">查询</el-button></div><el-tag effect="plain">路线名称全局唯一</el-tag></div>
    <el-table :data="rows" border height="580"><el-table-column prop="route_code" label="路线编号" width="130"/><el-table-column prop="route_name" label="路线名称" min-width="190"/><el-table-column prop="route_grade" label="路线等级" width="130"/><el-table-column prop="route_distance" label="规划里程（km）" width="150"><template #default="{row}">{{ row.route_distance?Number(row.route_distance/1000).toFixed(2):'—' }}</template></el-table-column><el-table-column prop="update_time" label="更新时间" min-width="170"/><el-table-column label="操作" width="170" fixed="right"><template #default="{row}"><el-button text type="primary" @click="openEdit(row)">编辑地图</el-button><el-popconfirm title="确认删除该路线？" @confirm="remove(row)"><template #reference><el-button text type="danger">删除</el-button></template></el-popconfirm></template></el-table-column></el-table>
    <div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total,prev,pager,next" @change="load"/></div>
    <el-dialog v-model="dialog" :title="editing?'编辑路线':'新增路线'" width="min(1120px,94vw)" destroy-on-close @opened="initMap">
      <div class="route-editor">
        <el-form label-position="top" class="route-form"><el-form-item label="路线编号"><el-input v-model="form.route_code" :disabled="Boolean(editing)" placeholder="例如 G75"/></el-form-item><el-form-item label="路线名称"><el-input v-model="form.route_name" placeholder="地图规划后自动带回，可人工修正"/></el-form-item><el-form-item label="路线等级"><el-select v-model="form.route_grade" style="width:100%" placeholder="请选择路线等级"><el-option v-for="item in grades" :key="item" :label="item" :value="item"/></el-select></el-form-item><div class="point-summary"><div><span>起点</span><b>{{ pointText(points[0]) }}</b></div><div><span>途经点</span><b>{{ Math.max(points.length-2,0) }} 个</b></div><div><span>终点</span><b>{{ pointText(points.at(-1),points.length<2) }}</b></div></div><div class="route-actions"><el-button @click="clearPoints"><Trash2 :size="15"/>清空选点</el-button><el-button type="primary" :loading="planning" :disabled="points.length<2" @click="planRoute"><Route :size="15"/>规划并识别</el-button></div><el-alert v-if="roads.length" type="success" :closable="false"><template #title>途经道路：{{ roads.join('、') }}</template></el-alert></el-form>
        <div class="map-shell"><div ref="mapContainer" class="route-map"></div><div class="map-hint">依次点击起点、途经点和终点；最后一个点作为终点</div></div>
      </div>
      <template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!form.route_name||!form.route_grade||!form.route_geometry" @click="save">保存路线</el-button></template>
    </el-dialog>
  </section>
</template>
<script setup>
import { nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus, Route, Trash2 } from 'lucide-vue-next'
import http from '../api/http'
const rows=ref([]),total=ref(0),page=ref(1),size=ref(10),keyword=ref(''),dialog=ref(false),editing=ref(null),saving=ref(false),planning=ref(false),mapContainer=ref(),points=ref([]),roads=ref([]),form=reactive({})
const grades=['高速公路','一级公路','二级公路','三级公路','四级公路'];let map=null,pointMarkers=[],routeLine=null
function loadAmap(){return new Promise((resolve,reject)=>{if(window.AMap)return resolve(window.AMap);const key=import.meta.env.VITE_AMAP_WEB_KEY;if(!key)return reject(new Error('未配置 VITE_AMAP_WEB_KEY'));window._AMapSecurityConfig={securityJsCode:import.meta.env.VITE_AMAP_SECURITY_CODE};const script=document.createElement('script');script.src=`https://webapi.amap.com/maps?v=2.0&key=${key}&plugin=AMap.Scale,AMap.ToolBar`;script.onload=()=>resolve(window.AMap);script.onerror=()=>reject(new Error('高德地图脚本加载失败'));document.head.appendChild(script)})}
async function load(){const data=await http.get('/routes',{params:{page:page.value,size:size.value,keyword:keyword.value}});rows.value=data.records;total.value=data.total}
function openCreate(){editing.value=null;Object.assign(form,{route_code:'',route_name:'',route_grade:'',route_geometry:'',route_distance:null,origin_longitude:null,origin_latitude:null,destination_longitude:null,destination_latitude:null,waypoints_json:'[]'});points.value=[];roads.value=[];dialog.value=true}
function openEdit(row){editing.value=row;Object.assign(form,row);const waypoints=parseJson(row.waypoints_json);points.value=[point(row.origin_longitude,row.origin_latitude),...waypoints,point(row.destination_longitude,row.destination_latitude)].filter(Boolean);roads.value=[];dialog.value=true}
async function initMap(){try{const AMap=await loadAmap();await nextTick();map?.destroy();map=new AMap.Map(mapContainer.value,{zoom:10,center:[106.551556,29.563009],viewMode:'2D'});map.addControl(new AMap.Scale());map.addControl(new AMap.ToolBar());map.on('click',event=>{if(points.value.length>=18){ElMessage.warning('最多设置16个途经点');return}points.value.push({longitude:event.lnglat.lng,latitude:event.lnglat.lat});renderPoints()});renderPoints();if(form.route_geometry)drawGeometry(form.route_geometry)}catch(error){ElMessage.error(error.message)}}
function renderPoints(){if(!map||!window.AMap)return;map.remove(pointMarkers);pointMarkers=points.value.map((item,index)=>new window.AMap.Marker({map,position:[item.longitude,item.latitude],label:{content:index===0?'起点':index===points.value.length-1?'终点':`途经${index}`,direction:'top'},draggable:true}));pointMarkers.forEach((marker,index)=>marker.on('dragend',event=>{points.value[index]={longitude:event.lnglat.lng,latitude:event.lnglat.lat};renderPoints()}));if(pointMarkers.length)map.setFitView(pointMarkers,false,[70,70,70,70],13)}
function drawGeometry(geometry){if(!map||!window.AMap)return;if(routeLine)map.remove(routeLine);const path=String(geometry).split(';').map(x=>x.split(',').map(Number)).filter(x=>x.length===2&&x.every(Number.isFinite));routeLine=new window.AMap.Polyline({map,path,strokeColor:'#0f766e',strokeWeight:7,strokeOpacity:.9,showDir:true});if(path.length)map.setFitView([routeLine],false,[60,60,60,60],13)}
async function planRoute(){planning.value=true;try{const result=await http.post('/routes/plan',{points:points.value});form.route_name=result.route_name||form.route_name;form.route_grade=result.route_grade||form.route_grade;form.route_geometry=result.route_geometry;form.route_distance=result.route_distance;form.origin_longitude=points.value[0].longitude;form.origin_latitude=points.value[0].latitude;form.destination_longitude=points.value.at(-1).longitude;form.destination_latitude=points.value.at(-1).latitude;form.waypoints_json=JSON.stringify(points.value.slice(1,-1));roads.value=result.roads||[];drawGeometry(result.route_geometry);if(!result.route_grade)ElMessage.warning('高德未返回公路技术等级，请人工确认路线等级')}finally{planning.value=false}}
async function save(){saving.value=true;try{if(editing.value)await http.put(`/routes/${editing.value.route_code}`,form);else await http.post('/routes',form);ElMessage.success('路线保存成功');dialog.value=false;await load()}finally{saving.value=false}}
async function remove(row){await http.delete(`/routes/${row.route_code}`);ElMessage.success('删除成功');await load()}
function clearPoints(){points.value=[];form.route_geometry='';roads.value=[];if(map){map.remove(pointMarkers);if(routeLine)map.remove(routeLine)}pointMarkers=[];routeLine=null}
function point(lon,lat){return lon!==null&&lon!==undefined&&lat!==null&&lat!==undefined?{longitude:Number(lon),latitude:Number(lat)}:null}function parseJson(value){try{return JSON.parse(value||'[]')}catch{return[]}}function pointText(value,empty=false){return!value||empty?'未设置':`${Number(value.longitude).toFixed(6)}, ${Number(value.latitude).toFixed(6)}`}
onMounted(load);onBeforeUnmount(()=>map?.destroy())
</script>
<style scoped>
.resource-heading{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #dbe3ec;padding-bottom:14px;margin-bottom:14px}.resource-heading span{color:#0f766e;font-size:12px;font-weight:700}.resource-heading h2{margin:5px 0 0}.resource-heading .el-button{display:flex;gap:6px}.pager{display:flex;justify-content:flex-end;margin-top:14px}.route-editor{display:grid;grid-template-columns:340px 1fr;gap:14px}.route-form{border:1px solid #dbe3ec;padding:16px;border-radius:8px}.map-shell{height:610px;position:relative;border:1px solid #dbe3ec}.route-map{width:100%;height:100%}.map-hint{position:absolute;left:14px;bottom:14px;background:#fff;padding:8px 11px;border-radius:6px;box-shadow:0 5px 18px rgba(15,23,42,.2);font-size:12px}.point-summary{display:grid;gap:7px;margin-bottom:14px}.point-summary div{padding:9px;background:#f8fafc;border:1px solid #e2e8f0}.point-summary span,.point-summary b{display:block}.point-summary span{font-size:11px;color:#64748b}.point-summary b{font-size:12px;margin-top:3px;word-break:break-all}.route-actions{display:flex;gap:8px;margin-bottom:14px}.route-actions .el-button{display:flex;gap:5px}@media(max-width:900px){.route-editor{grid-template-columns:1fr}.map-shell{height:520px}}
</style>
